cc_test(
  name = "symbol_table_test",
  srcs = ["symbol_table_test.cc"],
  size = "small",
  deps = [
       "//parser:symbol_table",
       "//third_party/gtest:gtest_main",
  ],
  copts = ["-std=c++14", "-Wall", "-Wextra", "--pedantic"],
)