cc_test(
  name = "container_util_test",
  srcs = ["container_util_test.cc"],
  size = "small",
  deps = [
       "//util:container_util",
       "//third_party/gtest:gtest_main",
  ],
)

cc_test(
  name = "text_colorizer_test",
  srcs = ["text_colorizer_test.cc"],
  size = "small",
  deps = [
       "//util:text_colorizer",
       "//third_party/gtest:gtest_main",
  ],
)

cc_test(
  name = "string_util_test",
  srcs = ["string_util_test.cc"],
  size = "small",
  deps = [
       "//util:string_util",
       "//third_party/gtest:gtest_main",
  ],
)


