package(default_visibility = ["//visibility:public"])

cc_library(
  name = "container_util",
  hdrs = ["container_util.h"],
)

cc_library(
  name = "text_colorizer",
  srcs = ["text_colorizer.cc"],
  hdrs = ["text_colorizer.h"],
)

cc_library(
  name = "string_util",
  srcs = ["string_util.cc"],
  hdrs = ["string_util.h"],
)