cc_test(
  name = "token_test",
  srcs = ["token_test.cc"],
  size = "small",
  deps = [
       "//tokens:token",
       "//third_party/gtest:gtest_main",
  ],
)

cc_test(
  name = "keyword_token_test",
  srcs = ["keyword_token_test.cc"],
  size = "small",
  deps = [
       "//tokens:keyword_token",
       "//third_party/gtest:gtest_main",
  ],
)

cc_test(
  name = "punctuation_token_test",
  srcs = ["punctuation_token_test.cc"],
  size = "small",
  deps = [
       "//tokens:punctuation_token",
       "//third_party/gtest:gtest_main",
  ],
)

cc_test(
  name = "rel_operator_token_test",
  srcs = ["rel_operator_token_test.cc"],
  size = "small",
  deps = [
       "//tokens:rel_operator_token",
       "//third_party/gtest:gtest_main",
  ],
)

cc_test(
  name = "add_operator_token_test",
  srcs = ["add_operator_token_test.cc"],
  size = "small",
  deps = [
       "//tokens:add_operator_token",
       "//third_party/gtest:gtest_main",
  ],
)

cc_test(
  name = "mul_operator_token_test",
  srcs = ["mul_operator_token_test.cc"],
  size = "small",
  deps = [
       "//tokens:mul_operator_token",
       "//third_party/gtest:gtest_main",
  ],
)

cc_test(
  name = "number_token_test",
  srcs = ["number_token_test.cc"],
  size = "small",
  deps = [
       "//tokens:number_token",
       "//third_party/gtest:gtest_main",
  ],
)

cc_test(
  name = "identifier_token_test",
  srcs = ["identifier_token_test.cc"],
  size = "small",
  deps = [
       "//tokens:identifier_token",
       "//third_party/gtest:gtest_main",
  ],
)

cc_test(
  name = "eof_token_test",
  srcs = ["eof_token_test.cc"],
  deps = [
       "//tokens:eof_token",
       "//third_party/gtest:gtest_main",
  ],
  copts = ["-std=c++14"],
)